### ISSUE TITLE
Presence of "?" in variant_category

### ISSUE THREAD

**Issue by sachalau** [farhat-lab/who-analysis#1]
https://github.com/farhat-lab/who-analysis/blob/1841ea8fe684cd2d9f102d6c2781149151a136f2/01_make_model_inputs.py#L162

Just saw that line.

I was incorrectly handling "stop_lost" variant until yesterday.
In the data you have, features have variant_category=stop_lost, predicted_effect=stop_lost
However that will change, and now stop_lost variant_category could take the following values : 

- p.Ter1828Glnext*?
- p.Ter277Leuext*?
- p.Ter277Cysext*?
- p.Ter423Glyext*?
- p.Ter423Cysext*?
- p.Ter423Cysext*?
- p.Ter2112Trpext*?
- p.Ter921Cysext*?

They will start matching at this line although they should. Shouldn't it be easier to match with "predicted_effec"="lof"?

**Comment by sanju99** [comment]
I've updated the LOF pooling function now to use the predicted_effect column. 

LOF for a (sample, gene) pair is now assigned if variant_category = deletion, predicted_effect = stop_gained, predicted_effect = start_lost, or there is a single frameshift mutation.
