### ISSUE TITLE
Multiple MICs for the same Sample and Media

### ISSUE THREAD

**Issue by sanju99** [farhat-lab/who-analysis#11]
Sacha, I'm seeing a very small number (<< 1% of samples) of samples that have multiple MICs recorded for the same sample and medium. This is a screenshot for Rifampicin. Is this a bug?
<img width="356" alt="Screen Shot 2022-11-15 at 7 15 38 PM" src="https://user-images.githubusercontent.com/32857277/202052347-01dabd0b-2e90-44d3-9cda-4034090447c3.png">

**Comment by mahafarhat** [comment]
Sanjana, I’m going to say let’s just drop those given the rarity. Investigating is probably not worth the time at this point. 

Maha

**Comment by sanju99** [comment]
Sounds good, will do. I'll update you if we decide something different tomorrow.

**Comment by sachalau** [comment]
Not a bug indeed, I received different submissions for identical samples
from time to time.
