### ISSUE TITLE
Asserting length of final df in 3rd step

### ISSUE THREAD

**Issue by sachalau** [farhat-lab/who-analysis#14]
Hi Sanjana,

https://github.com/farhat-lab/who-analysis/blob/944c41b7b9d2dd0cd8ee27a513f82e4612eb4cf3/03_model_analysis.py#L147

I've run into an error at that point for BDQ.

I have one more row in the final df (913 versus 912).

I think this could happen because, in v1, some variants were not properly normalized, and I think that some were called differently, but they are actually considered the same in v2. 

See for instance for BDQ, these are the variants that are duplicated in your data "who_confidence_2021.csv"

```
drug | confidence | mutation
-- | -- | --
BDQ | 3) Uncertain   significance | pepQ_p.Phe46Leu
BDQ | 3) Uncertain significance | pepQ_p.Phe46Leu
BDQ | 3) Uncertain   significance | Rv0678_p.Asp47fs
BDQ | 3) Uncertain significance | Rv0678_p.Asp47fs
BDQ | 3) Uncertain   significance | Rv0678_p.Ile67fs
BDQ | 3) Uncertain significance | Rv0678_p.Ile67fs
BDQ | 3) Uncertain   significance | Rv1979c_p.Val108fs
BDQ | 3) Uncertain significance | Rv1979c_p.Val108fs
```
It makes sense because these variants were not aggregated together in v1, so they appear more than once. Or simply because there are more than one mutation that lead to the same amino acid change (that's the case for pepQ_p.Phe46Leu).

And indeed the first variant (pepQ_p.Phe46Leu) appears twice in the result file (after I remove the assert on the number of rows)

**Comment by sanju99** [comment]
Thanks for pointing this out, Sacha. I will remake the `analysis/who_confidence_2021.csv` file after dropping duplicates and let you know when to pull the updates.

**Comment by sanju99** [comment]
I updated the file now. Let me know if it still causes problems. Sorry again for this, I didn't remove unnecessary columns before running `drop_duplicates()`, which caused this problem.

**Comment by sachalau** [comment]
Thanks a lot !

I think the other assert that failed was this one : 

https://github.com/farhat-lab/who-analysis/blob/ad0c63ce20b775fbf3defd8526bae34f911de3dc/04_compute_univariate_stats.py#L230

**Comment by sanju99** [comment]
I just ran this for Delamanid (because it's the smallest model) and didn't get any errors. I'm rerunning for bedaquiline to see if I get this assertion error.

**Comment by sanju99** [comment]
I reran all BDQ models and didn't get an error, so hopefully my most recent updates have fixed the length issue.
