### ISSUE TITLE
Pheno vs Geno sample numbers

### ISSUE THREAD

**Issue by sachalau** [farhat-lab/who-analysis#2]
https://github.com/farhat-lab/who-analysis/blob/792383b217954e6b40ce2fb9fedb5aefd449d0c9/sample_numbers.py#L141-L142

Should be true... I've seen the numbers do not add up in your summary csv.
I just checked for Isoniazid and all tier 1 genes, the numbers match, for the latest extraction... 
Maybe something went wrong with a previous one. We'll see if those still do not add up when you next update the data.

**Comment by sanju99** [comment]
Thanks, Sacha! I updated `samples_summary.csv` with the new data, and the phenos and genos match now.
