### ISSUE TITLE
p.Met1fs frameshift/start lost

### ISSUE THREAD

**Issue by sachalau** [farhat-lab/who-analysis#9]
https://github.com/farhat-lab/who-analysis/blob/a32bc2f28053b03b16b48919b7fdb4c310bb1dd0/01_make_model_inputs.py#L142-L144

I think this has been corrected since... Now all "p.Met1fs" variant categories should be associated with the effect "frameshift", and not "start lost", which you favoured in your correction. I don't think it's really important but it could change the outcome whether or not you cancel out multiple frameshifts in the same gene.

**Comment by sanju99** [comment]
Thank you for pointing this out. I will check for duplicated Met1fs entries and remove that sorting/dropping line so that this variant is associated with "frameshift."

**Comment by sanju99** [comment]
All good, thanks! I have removed this line now.

**Comment by sanju99** [comment]
Sacha, I'm seeing this issue again, but now for nonsense mutations (example in the screenshot). Should I preferentially keep rows annotated with `stop_gained` and `start_lost` over `frameshift`?

![Screen Shot 2022-11-08 at 12 24 30 PM](https://user-images.githubusercontent.com/32857277/200633362-25276ebb-1c02-4e54-bb13-ae27980a82a6.png)

**Comment by sachalau** [comment]
Ugh thanks, I'm sorry I wrote code a while ago to favour frameshift instead of stop_gained for those cases, seems I did not test it enough. I'll review that now.

**Comment by sachalau** [comment]
Regarding the position that's because there are 4 different variant that are associated with the predicted effect "frameshift" so they all appear. However, there is only one variant that is associated with the (uncurated) effect "frameshift&stop_gained". I was sure that my curation lead to frameshift being favoured upon stop_gained but I was wrong. I'll correct that.

**Comment by sachalau** [comment]
![image](https://user-images.githubusercontent.com/16240565/200636187-204b2cfd-9a5d-4839-9ab8-8d9d42d09992.png)

Here is the raw data from the database. It's actually four that have listed "frameshift_variant" and one of them that also has "stop_gained"

From next extraction, they will all be merged to predicted_effect = "frameshift".

**Comment by sanju99** [comment]
Okay thank you for fixing this! Let us know when the new data has been uploaded to AWS so we can pull.
